// Generated by model-training/train_and_export.py. Do not edit by hand.
// Feature order: peakG, minG, variance, postVariance, orientationChange, lowMotionRatio, durationMs

export const MODEL_META = {
  name: "VelaGuardDecisionTree",
  version: "1.0.0",
  maxDepth: 4,
  classes: ["fall", "immobility", "normal"],
  featureCount: 7
}

export function predict(features) {
  if (features[2] <= 0.030013723) {
    if (features[5] <= 0.81816101) {
      return {label: "normal", confidence: 1}
    } else {
      if (features[6] <= 3336.5211) {
        return {label: "immobility", confidence: 0.60234333}
      } else {
        return {label: "immobility", confidence: 1}
      }
    }
  } else {
    if (features[4] <= 0.39101994) {
      if (features[1] <= 0.24567758) {
        return {label: "fall", confidence: 0.84172662}
      } else {
        if (features[2] <= 0.40540738) {
          return {label: "normal", confidence: 0.98417529}
        } else {
          return {label: "normal", confidence: 0.7073955}
        }
      }
    } else {
      if (features[3] <= 0.076256741) {
        if (features[5] <= 0.36436877) {
          return {label: "fall", confidence: 0.93413174}
        } else {
          return {label: "fall", confidence: 0.99904156}
        }
      } else {
        return {label: "normal", confidence: 1}
      }
    }
  }
}
